# Generated by Django 4.2.7 on 2026-07-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('eracun', 'eRačun'), ('fiscalization', 'Fiskalizacija'), ('payment', 'Plaćanje'), ('shipping', 'Dostava')], max_length=20, verbose_name='Tip integracije')),
                ('provider', models.CharField(choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)')], max_length=20, verbose_name='Provider')),
                ('environment', models.CharField(choices=[('production', 'Produkcija'), ('test', 'Test'), ('staging', 'Staging'), ('sandbox', 'Sandbox')], default='production', max_length=20, verbose_name='Okruženje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Naziv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Integracija',
                'verbose_name_plural': 'Integracije',
            },
        ),
        migrations.AddConstraint(
            model_name='integrationconfig',
            constraint=models.UniqueConstraint(fields=('tenant', 'integration_type', 'provider', 'environment'), name='unique_integration_per_tenant_type_provider_env'),
        ),
        migrations.AddConstraint(
            model_name='integrationconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'integration_type', 'environment'), name='unique_active_integration_per_type_env'),
        ),
    ]
