# Generated by Django 4.2.7 on 2026-07-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('integrations', '0006_integrationoutboxmessage_pts_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationauditlog',
            name='provider',
            field=models.CharField(blank=True, choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('otp', 'OTP banka')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationauditlog',
            name='step',
            field=models.CharField(choices=[('document_built', 'Dokument izgrađen'), ('semantic_ok', 'Semantička validacija OK'), ('xsd_ok', 'XSD validacija OK'), ('schematron_ok', 'Schematron OK'), ('schematron_skipped', 'Schematron preskočen'), ('signed', 'UBL potpis'), ('outbound_sent', 'Izlazni poslan'), ('outbound_failed', 'Izlazni neuspješan'), ('fiscalized', 'Fiskaliziran'), ('fiscal_failed', 'Fiskalizacija neuspješna'), ('inbound_received', 'Ulazni AS4 zaprimljen'), ('expense_created', 'Ulazni trošak kreiran'), ('app_response_sent', 'ApplicationResponse poslan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('otp', 'OTP banka')], max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxmessage',
            name='provider',
            field=models.CharField(blank=True, choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('otp', 'OTP banka')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationoutboxmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
