# Generated by Django 4.2.7 on 2026-08-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_private_funds_claim'),
        ('tenants', '0007_create_finestar_tenant'),
        ('integrations', '0008_fiscal_prod_cutover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationauditlog',
            name='provider',
            field=models.CharField(blank=True, choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('fiskal_platform', 'Fiskal Platform'), ('otp', 'OTP banka')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='provider',
            field=models.CharField(choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('fiskal_platform', 'Fiskal Platform'), ('otp', 'OTP banka')], max_length=20, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='integrationoutboxmessage',
            name='provider',
            field=models.CharField(blank=True, choices=[('super', 'SUPER'), ('direct', 'Direktno (racunAI)'), ('mer', 'MER'), ('cis', 'CIS (Porezna)'), ('fiskal_platform', 'Fiskal Platform'), ('otp', 'OTP banka')], max_length=20),
        ),
        migrations.CreateModel(
            name='InboundGatewayDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_document_id', models.UUIDField(db_index=True)),
                ('bound_provider', models.CharField(blank=True, max_length=40)),
                ('provider_ref', models.CharField(blank=True, max_length=128)),
                ('taxpayer_oib', models.CharField(max_length=11)),
                ('rejection_capable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_document_link', to='expenses.expense')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Gateway inbound document link',
                'verbose_name_plural': 'Gateway inbound document links',
            },
        ),
        migrations.CreateModel(
            name='InboundEracunRejectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_document_id', models.UUIDField()),
                ('attempt_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=200)),
                ('reason_code', models.CharField(max_length=64)),
                ('reason_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('e_reporting_status', models.CharField(default='PENDING', max_length=32)),
                ('provider_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eracun_rejection_attempts', to='expenses.expense')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Inbound eRačun rejection attempt',
                'verbose_name_plural': 'Inbound eRačun rejection attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='inbounderacunrejectionattempt',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_inbound_eracun_rejection_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='inbounderacunrejectionattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('expense',), name='unique_pending_inbound_eracun_rejection_per_expense'),
        ),
    ]
