# Generated by Django 4.2.7 on 2025-09-07 10:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('asset', 'Imovina'), ('liability', 'Obveze'), ('equity', 'Glavnica'), ('revenue', 'Prihodi'), ('expense', 'Rashodi')], max_length=50, unique=True, verbose_name='Tip konta')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Tip konta',
                'verbose_name_plural': 'Tipovi kontova',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=10, unique=True, verbose_name='Šifra konta')),
                ('account_name', models.CharField(max_length=200, verbose_name='Naziv konta')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.accounttype', verbose_name='Tip konta')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounting.chartofaccounts', verbose_name='Nadređeni konto')),
            ],
            options={
                'verbose_name': 'Konto',
                'verbose_name_plural': 'Kontni plan',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='Broj temeljnice')),
                ('entry_date', models.DateField(verbose_name='Datum knjiženja')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('posted', 'Knjiženo'), ('reversed', 'Stornirano')], default='draft', max_length=10, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Opis knjiženja')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referenca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum knjiženja')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL, verbose_name='Knjižio')),
            ],
            options={
                'verbose_name': 'Temeljnica',
                'verbose_name_plural': 'Temeljnice',
                'ordering': ['-entry_date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Opis stavke')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Duguje')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Potražuje')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_lines', to='accounting.chartofaccounts', verbose_name='Konto')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry', verbose_name='Temeljnica')),
            ],
            options={
                'verbose_name': 'Stavka temeljnice',
                'verbose_name_plural': 'Stavke temeljnice',
            },
        ),
    ]
