# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('asset', 'Imovina'), ('liability', 'Obveze'), ('equity', 'Glavnica'), ('revenue', 'Prihodi'), ('expense', 'Rashodi')], max_length=50, verbose_name='Tip konta'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_code',
            field=models.CharField(max_length=10, verbose_name='Šifra konta'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_number',
            field=models.CharField(max_length=50, verbose_name='Broj temeljnice'),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_account_type_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='chartofaccounts',
            constraint=models.UniqueConstraint(fields=('tenant', 'account_code'), name='unique_account_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'entry_number'), name='unique_entry_number_per_tenant'),
        ),
    ]
