# Generated by Django 4.2.7 on 2026-07-03 01:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0006_vat_ledger_type_ira_ura'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv')),
                ('inventory_number', models.CharField(blank=True, max_length=50, verbose_name='Inventarni broj')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('registration_plate', models.CharField(blank=True, max_length=20, verbose_name='Registracija')),
                ('status', models.CharField(choices=[('in_preparation', 'U pripremi'), ('active', 'Aktivno'), ('disposed', 'Otpisano')], default='in_preparation', max_length=20, verbose_name='Status')),
                ('origin', models.CharField(choices=[('purchase', 'Nabava'), ('opening_balance', 'Početno stanje')], default='purchase', max_length=20, verbose_name='Porijeklo')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Nabavna vrijednost')),
                ('purchase_date', models.DateField(verbose_name='Datum nabave')),
                ('in_service_date', models.DateField(blank=True, null=True, verbose_name='Datum stavljanja u uporabu')),
                ('disposed_at', models.DateField(blank=True, null=True, verbose_name='Datum otpisa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_accumulated_depreciation', to='accounting.chartofaccounts', verbose_name='Konto ispravka vrijednosti')),
                ('activation_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_activation', to='accounting.journalentry', verbose_name='Temeljnica aktivacije')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_asset', to='accounting.chartofaccounts', verbose_name='Konto osnovnog sredstva')),
                ('construction_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_construction', to='accounting.chartofaccounts', verbose_name='Konto u pripremi')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_depreciation_expense', to='accounting.chartofaccounts', verbose_name='Konto troška amortizacije')),
                ('disposal_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_disposal', to='accounting.journalentry', verbose_name='Temeljnica otpisa')),
                ('purchase_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets_purchase', to='accounting.journalentry', verbose_name='Temeljnica nabave')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Osnovno sredstvo',
                'verbose_name_plural': 'Osnovna sredstva',
                'ordering': ['-purchase_date', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('tenant', 'vin'), name='unique_vin_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(condition=models.Q(('purchase_journal_entry__isnull', False)), fields=('purchase_journal_entry',), name='unique_purchase_journal_entry'),
        ),
    ]
