# Generated by Django 4.2.7 on 2026-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_fixed_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatledgerentry',
            name='entry_category',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('eu_acquisition', 'EU stjecanje'), ('import', 'Uvoz'), ('adjustment', 'Korekcija')], default='domestic', max_length=20, verbose_name='Kategorija stavke'),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Ručna korekcija'),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='vat_box',
            field=models.CharField(blank=True, choices=[('000', 'Ukupni promet u razdoblju oporezivanja'), ('100', 'Isporuke u RH po stopi 0% (osim izvoza)'), ('101', 'Isporuke dobara unutar EU'), ('102', 'Isporuke dobara u treće zemlje (izvoz)'), ('103', 'Obavljene usluge unutar EU'), ('104', 'Obavljene usluge u treće zemlje'), ('105', 'Isporuke NPS u RH'), ('106', 'Trosarinske naknade'), ('107', 'Posebni postupci oporezivanja'), ('108', 'Ostalo oslobođeno'), ('109', 'Ostalo neoporezivo'), ('110', 'Ostale isporuke'), ('111', 'Ukupno oslobođeno i neoporezivo'), ('200', 'Oporezive isporuke — ukupno'), ('201', 'Oporezive isporuke po stopi 5%'), ('202', 'Oporezive isporuke po stopi 13%'), ('203', 'Oporezive isporuke po stopi 25%'), ('204', 'Prodaja dobara na daljinu unutar EU'), ('205', 'Isporuke NPS unutar EU'), ('206', 'Montaža i instaliranje u drugoj državi članici'), ('207', 'Usluge B2B na koje primjenjuje primatelj'), ('208', 'Trostrani poslovi'), ('209', 'Prijenos porezne obveze'), ('210', 'Nekretnine'), ('211', 'Prodaja rabljenih dobara, umjetničkih djela i kolekcionarskih predmeta'), ('212', 'Putničke agencije (marža)'), ('213', 'Stjecanje unutar EU s ugradnjom u drugoj državi'), ('214', 'Isporuke putem elektroničkog sučelja'), ('215', 'Isporuke u okviru posebnog postupka OSS'), ('300', 'Ukupno pretporez'), ('301', 'Pretporez od isporuka u RH po stopi 5%'), ('302', 'Pretporez od isporuka u RH po stopi 13%'), ('303', 'Pretporez od isporuka u RH po stopi 25%'), ('304', 'Pretporez — uvoz'), ('305', 'Pretporez — stjecanje dobara unutar EU'), ('306', 'Pretporez — primljene usluge unutar EU'), ('307', 'Pretporez — primljene usluge B2B'), ('308', 'Pretporez — obveza u drugoj državi članici'), ('309', 'Pretporez — naknadno'), ('310', 'Pretporez — manji prijetvor'), ('311', 'Pretporez — posebni postupci'), ('312', 'Pretporez — ostalo'), ('313', 'Pretporez — ne priznat'), ('314', 'Pretporez — ostalo ulazno'), ('315', 'Nepriznati pretporez'), ('400', 'Obveza PDV-a (za uplatu) / povrat'), ('500', 'Ispravak pretporeza iz prethodnog razdoblja'), ('610', 'Stjecanje dobara unutar EU (osnovica)'), ('611', 'Stjecanje dobara unutar EU — PDV'), ('612', 'Primljene usluge unutar EU'), ('613', 'PDV na primljene usluge unutar EU'), ('614', 'Obveza na stjecanje'), ('615', 'Pretporez na stjecanje'), ('620', 'Ostale isporuke'), ('630', 'Prijenos dobara u drugu državu članicu'), ('640', 'Primljene isporuke — prijenos obveze'), ('650', 'Obavljene isporuke — prijenos obveze'), ('660', 'Nema prometa u razdoblju'), ('701', 'Marža — rabljena dobra'), ('702', 'Marža — umjetnička djela'), ('703', 'Marža — kolekcionarski predmeti'), ('704', 'Marža — antikviteti')], max_length=3, verbose_name='PDV polje (VATBox)'),
        ),
    ]
