# Generated by Django 4.2.7 on 2026-07-05 12:00

import accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_seed_taxoffice_backfill_address'),
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0008_vat_ledger_vat_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Verzija')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Nacrt'),
                            ('generated', 'Generirano'),
                            ('signed', 'Potpisano'),
                            ('submitted', 'Predano'),
                            ('superseded', 'Zamijenjeno'),
                            ('imported', 'Importirano'),
                        ],
                        default='generated',
                        max_length=12,
                        verbose_name='Status',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[
                            ('erp_generated', 'ERP generirano'),
                            ('imported', 'Importirano'),
                            ('manual_upload', 'Ručni upload'),
                        ],
                        default='erp_generated',
                        max_length=16,
                        verbose_name='Izvor',
                    ),
                ),
                ('schema_version', models.CharField(default='11.0', max_length=10, verbose_name='Verzija sheme')),
                ('mapping_version', models.PositiveSmallIntegerField(default=1, verbose_name='Verzija mapiranja')),
                ('payload_snapshot', models.JSONField(verbose_name='Snapshot payloada')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='Hash payloada')),
                (
                    'payload_json',
                    models.FileField(upload_to=accounting.models.vat_return_upload_to, verbose_name='payload.json'),
                ),
                (
                    'xml_unsigned',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounting.models.vat_return_upload_to,
                        verbose_name='Nepotpisani XML',
                    ),
                ),
                (
                    'xml_submitted',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounting.models.vat_return_upload_to,
                        verbose_name='Predani XML',
                    ),
                ),
                ('xml_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256 predanog XML-a')),
                (
                    'eporezna_identifier',
                    models.UUIDField(blank=True, null=True, verbose_name='ePorezna identifikator'),
                ),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum predaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                (
                    'prepared_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='vat_returns_prepared',
                        to='settings.responsibleperson',
                        verbose_name='Sastavio',
                    ),
                ),
                (
                    'superseded_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='supersedes',
                        to='accounting.vatreturn',
                        verbose_name='Zamijenjeno verzijom',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='tenants.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'vat_period',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='returns',
                        to='accounting.vatperiod',
                        verbose_name='PDV razdoblje',
                    ),
                ),
            ],
            options={
                'verbose_name': 'PDV obrazac',
                'verbose_name_plural': 'PDV obrasci',
                'ordering': ['-vat_period__year', '-vat_period__month', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='vatreturn',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'vat_period', 'version'),
                name='unique_vat_return_version_per_period',
            ),
        ),
    ]
