# Generated by Django 4.2.7 on 2026-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_vatreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatreturn',
            name='unsigned_xml_sha256',
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name='SHA256 nepotpisanog XML-a',
            ),
        ),
    ]
