# Generated by Django 4.2.7 on 2026-07-06 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import accounting.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0010_vatreturn_unsigned_xml_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatreturn',
            name='submission_confirmation',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounting.models.vat_return_upload_to,
                verbose_name='Potvrda predaje',
            ),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='submission_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('manual_ep', 'Ručna predaja (ePorezna)'),
                    ('api', 'ePorezna API'),
                    ('import', 'Import XML'),
                ],
                max_length=12,
                verbose_name='Način predaje',
            ),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vat_returns_submitted',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Predao',
            ),
        ),
        migrations.CreateModel(
            name='PdvSSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(verbose_name='Datum predaje')),
                ('eporezna_identifier', models.UUIDField(verbose_name='ePorezna identifikator')),
                (
                    'submission_method',
                    models.CharField(
                        choices=[
                            ('manual_ep', 'Ručna predaja (ePorezna)'),
                            ('api', 'ePorezna API'),
                            ('import', 'Import XML'),
                        ],
                        default='manual_ep',
                        max_length=12,
                        verbose_name='Način predaje',
                    ),
                ),
                (
                    'submission_confirmation',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounting.models.pdv_s_submission_upload_to,
                        verbose_name='Potvrda predaje',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                (
                    'submitted_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='pdv_s_submissions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Predao',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tenants.tenant',
                    ),
                ),
                (
                    'vat_period',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='pdv_s_submission',
                        to='accounting.vatperiod',
                        verbose_name='PDV razdoblje',
                    ),
                ),
            ],
            options={
                'verbose_name': 'PDV-S predaja',
                'verbose_name_plural': 'PDV-S predaje',
            },
        ),
    ]
