# Generated by Django 4.2.7 on 2026-07-06 17:00

from django.db import migrations, models


def backfill_submitted_version(apps, schema_editor):
    VATReturn = apps.get_model('accounting', 'VATReturn')
    for vat_return in VATReturn.objects.filter(
        status__in=('submitted', 'imported'),
        submitted_version__isnull=True,
    ):
        vat_return.submitted_version = vat_return.version
        vat_return.save(update_fields=['submitted_version'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_vatreturn_submission_pdvssubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vatreturn',
            name='submitted_version',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Verzija drafta u trenutku predaje (audit trag).',
                null=True,
                verbose_name='Predana verzija',
            ),
        ),
        migrations.RunPython(backfill_submitted_version, migrations.RunPython.noop),
    ]
