# Generated by Django 4.2.7 on 2026-07-10 00:00

import accounting.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_seed_taxoffice_backfill_address'),
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0017_subledgeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZPReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Verzija')),
                ('schema_version', models.CharField(default='1.0', max_length=10, verbose_name='Verzija sheme')),
                ('mapping_version', models.PositiveSmallIntegerField(default=1, verbose_name='Verzija mapiranja')),
                ('payload_snapshot', models.JSONField(verbose_name='Snapshot payloada')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='Hash payloada')),
                (
                    'payload_json',
                    models.FileField(upload_to=accounting.models.zp_return_upload_to, verbose_name='payload.json'),
                ),
                (
                    'xml_unsigned',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounting.models.zp_return_upload_to,
                        verbose_name='Nepotpisani XML',
                    ),
                ),
                (
                    'xml_submitted',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounting.models.zp_return_upload_to,
                        verbose_name='Predani XML',
                    ),
                ),
                (
                    'unsigned_xml_sha256',
                    models.CharField(blank=True, max_length=64, verbose_name='SHA256 nepotpisanog XML-a'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                (
                    'prepared_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='zp_returns_prepared',
                        to='settings.responsibleperson',
                        verbose_name='Sastavio',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='tenants.tenant',
                        verbose_name='Tenant',
                    ),
                ),
                (
                    'vat_period',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='zp_returns',
                        to='accounting.vatperiod',
                        verbose_name='PDV razdoblje',
                    ),
                ),
            ],
            options={
                'verbose_name': 'ZP obrazac',
                'verbose_name_plural': 'ZP obrasci',
                'ordering': ['-vat_period__year', '-vat_period__month', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='zpreturn',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'vat_period', 'version'),
                name='unique_zp_return_version_per_period',
            ),
        ),
    ]
