# Generated by Django 4.2.7 on 2026-07-10

import decimal

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0018_zpreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_method',
            field=models.CharField(
                choices=[('linear', 'Linearna')],
                default='linear',
                max_length=20,
                verbose_name='Metoda amortizacije',
            ),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='residual_value',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                verbose_name='Ostatak vrijednosti',
            ),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='useful_life_months',
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name='Trajnost (mjeseci)',
            ),
        ),
        migrations.CreateModel(
            name='DepreciationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Godina')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mjesec')),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(decimal.Decimal('0.01'))],
                        verbose_name='Iznos amortizacije',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                (
                    'fixed_asset',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='depreciation_schedules',
                        to='accounting.fixedasset',
                        verbose_name='Osnovno sredstvo',
                    ),
                ),
                (
                    'journal_entry',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='depreciation_schedules',
                        to='accounting.journalentry',
                        verbose_name='Temeljnica amortizacije',
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='tenants.tenant',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Plan amortizacije',
                'verbose_name_plural': 'Planovi amortizacije',
                'ordering': ['year', 'month'],
            },
        ),
        migrations.AddConstraint(
            model_name='depreciationschedule',
            constraint=models.UniqueConstraint(
                fields=('fixed_asset', 'year', 'month'),
                name='unique_depreciation_per_asset_period',
            ),
        ),
    ]
