# Generated by Django 4.2.7 on 2026-08-18 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_ledger_origin(apps, schema_editor):
    VATLedgerEntry = apps.get_model('accounting', 'VATLedgerEntry')
    VATLedgerEntry.objects.filter(is_manual=True).update(origin='manual')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0019_fixed_asset_depreciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATProjectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[
                        ('PREPARED', 'Prepared'),
                        ('APPLIED', 'Applied'),
                        ('REJECTED', 'Rejected'),
                        ('STALE', 'Stale'),
                        ('FAILED', 'Failed'),
                    ],
                    max_length=16,
                    verbose_name='Status',
                )),
                ('engine_version', models.PositiveSmallIntegerField(verbose_name='Verzija enginea')),
                ('mapping_version', models.PositiveSmallIntegerField(verbose_name='Verzija mapiranja')),
                ('input_fingerprint', models.CharField(max_length=64, verbose_name='Ulazni fingerprint')),
                ('output_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='Izlazni fingerprint')),
                ('classified_count', models.PositiveIntegerField(default=0)),
                ('not_relevant_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('rejection_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='vat_projection_runs',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('tenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(app_label)s_%(class)s_set',
                    to='tenants.tenant',
                    verbose_name='Tenant',
                )),
                ('vat_period', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='projection_runs',
                    to='accounting.vatperiod',
                    verbose_name='PDV razdoblje',
                )),
            ],
            options={
                'verbose_name': 'PDV projection run',
                'verbose_name_plural': 'PDV projection runovi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='mapping_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Verzija mapiranja'),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='origin',
            field=models.CharField(
                choices=[
                    ('legacy', 'Legacy generator'),
                    ('engine', 'Tax classification engine'),
                    ('manual', 'Manual correction'),
                ],
                default='legacy',
                max_length=16,
                verbose_name='Podrijetlo retka',
            ),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='source_line_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID izvorne stavke'),
        ),
        migrations.AddField(
            model_name='vatledgerentry',
            name='projection_run',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='ledger_entries',
                to='accounting.vatprojectionrun',
                verbose_name='Projection run',
            ),
        ),
        migrations.RunPython(backfill_ledger_origin, migrations.RunPython.noop),
    ]
