# Generated by Django 4.2.7 on 2026-08-20 07:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0008_partner_country_code_not_null_uniques'),
        ('payments', '0006_bankaccount_ledger_account'),
        ('tenants', '0007_create_finestar_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0021_journalentry_replaces_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Broj')),
                ('direction', models.CharField(choices=[('given', 'Dana kaucija')], default='given', max_length=10, verbose_name='Smjer')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Iznos')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('deposit_date', models.DateField(verbose_name='Datum davanja')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('open', 'Otvoreno'), ('returned', 'Vraćeno'), ('reversed', 'Stornirano'), ('cancelled', 'Otkazano')], default='draft', max_length=12, verbose_name='Workflow status')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referenca')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Datum povrata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Kaucija / depozit',
                'verbose_name_plural': 'Kaucije / depoziti',
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='subledgeritem',
            new_name='accounting__tenant__9032fc_idx',
            old_name='accounting__tenant__8a1f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='subledgeritem',
            new_name='accounting__tenant__f159a5_idx',
            old_name='accounting__tenant__c4e9b1_idx',
        ),
        migrations.AlterField(
            model_name='depreciationschedule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='pdvsreturn',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='subledgerallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='subledgeritem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='submissionevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='vatledgerentry',
            name='entry_category',
            field=models.CharField(choices=[('domestic', 'Domestic'), ('eu_supply', 'EU isporuka'), ('eu_acquisition', 'EU stjecanje'), ('oss_supply', 'OSS/IOSS e-trgovina'), ('import', 'Uvoz'), ('adjustment', 'Korekcija')], default='domestic', max_length=20, verbose_name='Kategorija stavke'),
        ),
        migrations.AlterField(
            model_name='vatledgerentry',
            name='vat_box',
            field=models.CharField(blank=True, choices=[('000', 'Ukupni promet u razdoblju oporezivanja'), ('100', 'Isporuke u RH po stopi 0% (osim izvoza)'), ('101', 'Isporuke dobara unutar EU'), ('102', 'Isporuke dobara u treće zemlje (izvoz)'), ('103', 'Obavljene usluge unutar EU'), ('104', 'Obavljene usluge u treće zemlje'), ('105', 'Isporuke NPS u RH'), ('106', 'Trosarinske naknade'), ('107', 'Posebni postupci oporezivanja'), ('108', 'Ostalo oslobođeno'), ('109', 'Ostalo neoporezivo'), ('110', 'Ostale isporuke'), ('111', 'Ukupno oslobođeno i neoporezivo'), ('200', 'Oporezive isporuke — ukupno'), ('201', 'Oporezive isporuke po stopi 5%'), ('202', 'Oporezive isporuke po stopi 13%'), ('203', 'Oporezive isporuke po stopi 25%'), ('204', 'Prodaja dobara na daljinu unutar EU'), ('205', 'Isporuke NPS unutar EU'), ('206', 'Montaža i instaliranje u drugoj državi članici'), ('207', 'Stjecanje dobara unutar EU po stopi 25% (II.7)'), ('208', 'Trostrani poslovi'), ('209', 'Prijenos porezne obveze'), ('210', 'Primljene usluge unutar EU (B2B)'), ('211', 'Prodaja rabljenih dobara, umjetničkih djela i kolekcionarskih predmeta'), ('212', 'Putničke agencije (marža)'), ('213', 'Stjecanje unutar EU s ugradnjom u drugoj državi'), ('214', 'Isporuke putem elektroničkog sučelja'), ('215', 'Isporuke u okviru posebnog postupka OSS'), ('300', 'Ukupno pretporez'), ('301', 'Pretporez od isporuka u RH po stopi 5%'), ('302', 'Pretporez od isporuka u RH po stopi 13%'), ('303', 'Pretporez od isporuka u RH po stopi 25%'), ('304', 'Pretporez — uvoz'), ('305', 'Pretporez — stjecanje dobara unutar EU'), ('306', 'Pretporez — primljene usluge unutar EU'), ('307', 'Pretporez od stjecanja dobara unutar EU po stopi 25% (III.7)'), ('308', 'Pretporez — obveza u drugoj državi članici'), ('309', 'Pretporez — prijenos porezne obveze'), ('310', 'Pretporez — manji prijetvor'), ('311', 'Pretporez — posebni postupci'), ('312', 'Pretporez — ostalo'), ('313', 'Pretporez — ne priznat'), ('314', 'Pretporez — ostalo ulazno'), ('315', 'Nepriznati pretporez'), ('400', 'Obveza PDV-a (za uplatu) / povrat'), ('500', 'Ispravak pretporeza iz prethodnog razdoblja'), ('610', 'Ispravak pretporeza — ukupno (VIII.1)'), ('611', 'Ispravak pretporeza — nabava nekretnina (VIII.1.1)'), ('612', 'Ispravak pretporeza — ostalo (VIII.1)'), ('613', 'Ispravak pretporeza — PDV komponenta (VIII.1)'), ('614', 'Ispravak pretporeza — nabava ostale DI (VIII.1.4)'), ('615', 'Ispravak pretporeza — prodaja ostale DI (VIII.1.5)'), ('620', 'Ostale isporuke'), ('630', 'Prijenos dobara u drugu državu članicu'), ('640', 'Primljene isporuke — prijenos obveze'), ('650', 'Obavljene isporuke — prijenos obveze'), ('660', 'Nema prometa u razdoblju'), ('701', 'Marža — rabljena dobra'), ('702', 'Marža — umjetnička djela'), ('703', 'Marža — kolekcionarski predmeti'), ('704', 'Marža — antikviteti')], max_length=3, verbose_name='PDV polje (VATBox)'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deposits', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='given_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_given_for', to='accounting.journalentry', verbose_name='JE davanja'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='partners.partner', verbose_name='Partner'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='return_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_returns', to='payments.bankaccount', verbose_name='Račun povrata'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='return_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_return_for', to='accounting.journalentry', verbose_name='JE povrata'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='reverse_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_reverse_for', to='accounting.journalentry', verbose_name='JE storna'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_deposit_number_per_tenant'),
        ),
    ]
