# Generated by Django 4.2.7 on 2026-08-20 14:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partners', '0008_partner_country_code_not_null_uniques'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounting', '0022_deposit_kaucija'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFundsClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='Broj')),
                ('claim_type', models.CharField(choices=[('supplier_payment', 'Plaćanje dobavljaču privatnim sredstvima'), ('deposit_funding', 'Financiranje kaucije privatnim sredstvima')], max_length=32, verbose_name='Tip')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Iznos')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('claim_date', models.DateField(verbose_name='Datum događaja')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('posted', 'Proknjiženo'), ('cancelled', 'Otkazano')], default='draft', max_length=12, verbose_name='Status')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referenca')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('related_object_id', models.PositiveIntegerField(verbose_name='ID povezanog dokumenta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_private_funds_claims', to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_funds_claims', to='accounting.journalentry', verbose_name='JE')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_funds_claims', to='partners.partner', verbose_name='Vjerovnik (Partner)')),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_funds_claim_related', to='contenttypes.contenttype', verbose_name='Tip povezanog dokumenta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Zahtjev privatnih sredstava',
                'verbose_name_plural': 'Zahtjevi privatnih sredstava',
                'ordering': ['-claim_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='privatefundsclaim',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_private_funds_claim_number_per_tenant'),
        ),
    ]
