# Generated by Django 4.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0023_private_funds_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssetJournalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('dependent_cost', 'Ovisni trošak'), ('payment', 'Plaćanje'), ('other', 'Ostalo')], max_length=20, verbose_name='Uloga')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('fixed_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_links', to='accounting.fixedasset', verbose_name='Osnovno sredstvo')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_links', to='accounting.journalentry', verbose_name='Temeljnica')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Veza imovine i temeljnice',
                'verbose_name_plural': 'Veze imovine i temeljnica',
            },
        ),
        migrations.AddConstraint(
            model_name='fixedassetjournallink',
            constraint=models.UniqueConstraint(fields=('fixed_asset', 'journal_entry'), name='unique_fixed_asset_journal_link'),
        ),
    ]
