# Generated by Django 4.2.7 on 2026-08-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0024_fixed_asset_journal_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('registration_plate', models.CharField(blank=True, max_length=20, verbose_name='Registracija')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('fixed_asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='accounting.fixedasset', verbose_name='Osnovno sredstvo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Vozilo',
                'verbose_name_plural': 'Vozila',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('vin', ''), _negated=True), fields=('tenant', 'vin'), name='unique_vehicle_vin_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('vin', ''), ('registration_plate', ''), _negated=True), name='vehicle_requires_vin_or_plate'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('vin', ''), ('vin__regex', '^[A-HJ-NPR-Z0-9]{17}$'), _connector='OR'), name='vehicle_vin_format'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('registration_plate', ''), models.Q(('registration_plate__regex', '^\\s|\\s$'), _negated=True), _connector='OR'), name='vehicle_plate_not_padded'),
        ),
    ]
