# Generated by Django 4.2.7 on 2026-09-15 12:52

import accounting.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_companysettings_vat_registration_status'),
        ('tenants', '0007_create_finestar_tenant'),
        ('accounting', '0029_postingrule_eu_rc_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TZ2Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveSmallIntegerField(verbose_name='Porezna godina')),
                ('version', models.PositiveSmallIntegerField(verbose_name='Verzija')),
                ('schema_version', models.CharField(default='1.0', max_length=10, verbose_name='Verzija sheme')),
                ('mapping_version', models.PositiveSmallIntegerField(default=1, verbose_name='Verzija mapiranja')),
                ('payload_snapshot', models.JSONField(verbose_name='Snapshot payloada')),
                ('payload_hash', models.CharField(max_length=64, verbose_name='Hash payloada')),
                ('payload_json', models.FileField(upload_to=accounting.models.tz2_return_upload_to, verbose_name='payload.json')),
                ('xml_unsigned', models.FileField(blank=True, null=True, upload_to=accounting.models.tz2_return_upload_to, verbose_name='Nepotpisani XML')),
                ('xml_submitted', models.FileField(blank=True, null=True, upload_to=accounting.models.tz2_return_upload_to, verbose_name='Predani XML')),
                ('unsigned_xml_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA256 nepotpisanog XML-a')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tz2_returns_prepared', to='settings.responsibleperson', verbose_name='Sastavio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'TZ 2 obrazac',
                'verbose_name_plural': 'TZ 2 obrasci',
                'ordering': ['-tax_year', '-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='tz2return',
            constraint=models.UniqueConstraint(fields=('tenant', 'tax_year', 'version'), name='unique_tz2_return_version_per_year'),
        ),
    ]
