# Generated by Django 4.2.7 on 2025-09-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Dnevnik promjena', 'verbose_name_plural': 'Dnevnik promjena'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Korisnički profil', 'verbose_name_plural': 'Korisnički profili'},
        ),
    ]
