# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('accounts', '0003_alter_auditlog_options_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
