# Generated by Django 4.2.7 on 2025-09-07 11:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Šifra partnera')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv partnera')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Kratki naziv')),
                ('partner_type', models.CharField(choices=[('customer', 'Kupac'), ('supplier', 'Dobavljač'), ('both', 'Kupac i dobavljač'), ('other', 'Ostalo')], max_length=20, verbose_name='Tip partnera')),
                ('status', models.CharField(choices=[('active', 'Aktivan'), ('inactive', 'Neaktivan'), ('blocked', 'Blokiran'), ('prospect', 'Potencijalni')], default='active', max_length=10, verbose_name='Status')),
                ('tax_number', models.CharField(max_length=20, unique=True, verbose_name='OIB')),
                ('vat_number', models.CharField(blank=True, max_length=30, verbose_name='PDV broj')),
                ('registration_number', models.CharField(blank=True, max_length=30, verbose_name='Matični broj')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('city', models.CharField(max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Poštanski broj')),
                ('country', models.CharField(default='Hrvatska', max_length=100, verbose_name='Država')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobitel')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('website', models.URLField(blank=True, verbose_name='Web stranica')),
                ('payment_terms', models.IntegerField(default=30, verbose_name='Uvjeti plaćanja (dani)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kreditni limit')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Popust (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Interne napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partneri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('customer', 'Kupac'), ('supplier', 'Dobavljač'), ('both', 'Kupac i dobavljač'), ('other', 'Ostalo')], max_length=20, unique=True, verbose_name='Tip partnera')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
            ],
            options={
                'verbose_name': 'Tip partnera',
                'verbose_name_plural': 'Tipovi partnera',
            },
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('general', 'Općenito'), ('sales', 'Prodaja'), ('purchasing', 'Nabava'), ('accounting', 'Računovodstvo'), ('technical', 'Tehnička podrška'), ('management', 'Upravljanje')], default='general', max_length=15, verbose_name='Tip kontakta')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=50, verbose_name='Prezime')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pozicija')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Odjel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Mobitel')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarni kontakt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='partners.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Kontakt partnera',
                'verbose_name_plural': 'Kontakti partnera',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Naziv banke')),
                ('bic', models.CharField(max_length=50, verbose_name='BIC/SWIFT kod')),
                ('iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT kod')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Primarni račun')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='partners.partner', verbose_name='Partner')),
            ],
            options={
                'verbose_name': 'Bankovni račun partnera',
                'verbose_name_plural': 'Bankovni računi partnera',
                'ordering': ['-is_primary', 'bank_name'],
            },
        ),
    ]
