# Generated by Django 4.2.7 on 2025-09-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerbankaccount',
            name='swift_code',
        ),
    ]
