# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('partners', '0002_remove_partnerbankaccount_swift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Šifra partnera'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_number',
            field=models.CharField(max_length=20, verbose_name='OIB'),
        ),
        migrations.AlterField(
            model_name='partnertype',
            name='name',
            field=models.CharField(choices=[('customer', 'Kupac'), ('supplier', 'Dobavljač'), ('both', 'Kupac i dobavljač'), ('other', 'Ostalo')], max_length=20, verbose_name='Tip partnera'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('tenant', 'partner_code'), name='unique_partner_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('tenant', 'tax_number'), name='unique_partner_tax_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='partnertype',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_partner_type_per_tenant'),
        ),
    ]
