# Generated by Django 4.2.7 on 2025-09-07 10:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv tvrtke')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('city', models.CharField(max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Poštanski broj')),
                ('country', models.CharField(default='Croatia', max_length=100, verbose_name='Država')),
                ('tax_number', models.CharField(max_length=20, unique=True, verbose_name='OIB')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
            ],
            options={
                'verbose_name': 'Tvrtka',
                'verbose_name_plural': 'Tvrtke',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Broj računa')),
                ('invoice_type', models.CharField(choices=[('outgoing', 'Izlazni'), ('incoming', 'Ulazni')], max_length=10, verbose_name='Tip računa')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('sent', 'Poslan'), ('paid', 'Plaćen'), ('overdue', 'Dospijeće prošlo'), ('cancelled', 'Otkazan')], default='draft', max_length=10, verbose_name='Status')),
                ('issue_date', models.DateField(verbose_name='Datum izdavanja')),
                ('due_date', models.DateField(verbose_name='Datum dospijeća')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Datum usluge')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Osnovica')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Iznos PDV-a')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ukupan iznos')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('company_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_sent', to='invoices.company', verbose_name='Tvrtka izdavatelj')),
                ('company_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='invoices.company', verbose_name='Tvrtka primatelj')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
            ],
            options={
                'verbose_name': 'Račun',
                'verbose_name_plural': 'Računi',
                'ordering': ['-issue_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Naziv stavke')),
                ('description', models.TextField(blank=True, verbose_name='Opis stavke')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Količina')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Jedinična cijena')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Stopa PDV-a (%)')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ukupno')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='Račun')),
            ],
            options={
                'verbose_name': 'Stavka računa',
                'verbose_name_plural': 'Stavke računa',
            },
        ),
    ]
