# Generated by Django 4.2.7 on 2025-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv klijenta')),
                ('address', models.TextField(verbose_name='Adresa')),
                ('city', models.CharField(max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Poštanski broj')),
                ('country', models.CharField(default='Croatia', max_length=100, verbose_name='Država')),
                ('tax_number', models.CharField(max_length=20, unique=True, verbose_name='OIB')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
            ],
            options={
                'verbose_name': 'Klijent',
                'verbose_name_plural': 'Klijenti',
                'ordering': ['name'],
            },
        ),
    ]
