# Generated by Django 4.2.7 on 2025-09-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_remove_partnerbankaccount_swift_code'),
        ('invoices', '0002_add_client_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_sent', to='partners.partner', verbose_name='Izdavatelj (partner)'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_received', to='partners.partner', verbose_name='Primatelj (partner)'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
