# Generated by Django 4.2.7 on 2025-09-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_delete_client_alter_invoice_company_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
    ]
