# Generated by Django 4.2.7 on 2025-09-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='company_from',
        ),
    ]
