# Generated by Django 4.2.7 on 2025-09-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_responsibleperson'),
        ('invoices', '0007_alter_invoice_subtotal_alter_invoice_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='Odgovorna osoba za ovaj račun', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.responsibleperson', verbose_name='Odgovorna osoba'),
        ),
    ]
