# Generated by Django 4.2.7 on 2025-09-07 10:18

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Naziv kategorije')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
            ],
            options={
                'verbose_name': 'Kategorija troška',
                'verbose_name_plural': 'Kategorije troškova',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv dobavljača')),
                ('address', models.TextField(blank=True, verbose_name='Adresa')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Grad')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Poštanski broj')),
                ('country', models.CharField(default='Croatia', max_length=100, verbose_name='Država')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='OIB')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
            ],
            options={
                'verbose_name': 'Dobavljač',
                'verbose_name_plural': 'Dobavljači',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=50, unique=True, verbose_name='Broj troška')),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('submitted', 'Poslan'), ('approved', 'Odobren'), ('paid', 'Plaćen'), ('rejected', 'Odbačen')], default='draft', max_length=10, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Iznos')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Iznos PDV-a')),
                ('currency', models.CharField(default='HRK', max_length=3, verbose_name='Valuta')),
                ('expense_date', models.DateField(verbose_name='Datum troška')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Datum dospijeća')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Broj računa/potvrde')),
                ('description', models.TextField(verbose_name='Opis troška')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Odobrio')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.expensecategory', verbose_name='Kategorija')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expenses.supplier', verbose_name='Dobavljač')),
            ],
            options={
                'verbose_name': 'Trošak',
                'verbose_name_plural': 'Troškovi',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
    ]
