# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_number',
            field=models.CharField(max_length=50, verbose_name='Broj troška'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naziv kategorije'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('tenant', 'expense_number'), name='unique_expense_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_expense_category_per_tenant'),
        ),
    ]
