# Generated by Django 4.2.7 on 2026-06-09 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import expenses.models
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_create_finestar_tenant'),
        ('expenses', '0004_expense_category_default_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=expenses.models.expense_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='Dozvoljen je samo PDF format.'), expenses.validators.validate_pdf_file_size, expenses.validators.validate_pdf_content], verbose_name='PDF prilog')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Originalni naziv datoteke')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum učitavanja')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='expenses.expense', verbose_name='Trošak')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Učitao')),
            ],
            options={
                'verbose_name': 'Prilog troška',
                'verbose_name_plural': 'Prilozi troškova',
                'ordering': ['-created_at'],
            },
        ),
    ]
