# Generated by Django 4.2.7 on 2026-07-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0007_create_finestar_tenant'),
        ('expenses', '0005_expenseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('card', 'Kartica'),
                    ('cash', 'Gotovina'),
                    ('transfer', 'Transfer'),
                    ('other', 'Ostalo'),
                ],
                max_length=20,
                verbose_name='Način plaćanja',
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(
                choices=[
                    ('manual', 'Ručno'),
                    ('super', 'SUPER'),
                    ('f1_csv', 'F1 CSV'),
                    ('ocr', 'OCR'),
                    ('email', 'E-mail'),
                ],
                default='manual',
                max_length=20,
                verbose_name='Izvor',
            ),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(
                    choices=[
                        ('manual', 'Ručno'),
                        ('super', 'SUPER'),
                        ('f1_csv', 'F1 CSV'),
                        ('ocr', 'OCR'),
                        ('email', 'E-mail'),
                    ],
                    max_length=20,
                    verbose_name='Izvor',
                )),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Datoteka')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum učitavanja')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('rows_total', models.PositiveIntegerField(default=0, verbose_name='Ukupno redaka')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='Kreirano')),
                ('duplicates_count', models.PositiveIntegerField(default=0, verbose_name='Duplikata')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Grešaka')),
                ('report_payload', models.JSONField(blank=True, default=dict, verbose_name='Izvještaj')),
                ('tenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(app_label)s_%(class)s_set',
                    to='tenants.tenant',
                    verbose_name='Tenant',
                )),
                ('uploaded_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='expense_import_batches',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Učitao',
                )),
            ],
            options={
                'verbose_name': 'Import batch',
                'verbose_name_plural': 'Import batch-evi',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseImportMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(
                    choices=[
                        ('manual', 'Ručno'),
                        ('super', 'SUPER'),
                        ('f1_csv', 'F1 CSV'),
                        ('ocr', 'OCR'),
                        ('email', 'E-mail'),
                    ],
                    max_length=20,
                    verbose_name='Izvor',
                )),
                ('external_id', models.CharField(max_length=255, verbose_name='Vanjski ID')),
                ('jir', models.CharField(blank=True, max_length=64, verbose_name='JIR')),
                ('super_guid', models.CharField(blank=True, max_length=64, verbose_name='SUPER GUID')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Sirovi podaci')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('batch', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='metadata_rows',
                    to='expenses.importbatch',
                    verbose_name='Batch',
                )),
                ('expense', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='import_metadata',
                    to='expenses.expense',
                    verbose_name='Trošak',
                )),
                ('tenant', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(app_label)s_%(class)s_set',
                    to='tenants.tenant',
                    verbose_name='Tenant',
                )),
            ],
            options={
                'verbose_name': 'Import metapodatak',
                'verbose_name_plural': 'Import metapodaci',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='expenseimportmetadata',
            constraint=models.UniqueConstraint(
                fields=('tenant', 'source', 'external_id'),
                name='unique_expense_import_external_id_per_tenant',
            ),
        ),
    ]
