# Generated by Django 4.2.7 on 2026-08-20 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import expenses.models
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('partners', '0008_partner_country_code_not_null_uniques'),
        ('expenses', '0010_incominginvoiceimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepayer',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_payers', to='partners.partner', verbose_name='Povezani Partner (MDM)'),
        ),
        migrations.AlterField(
            model_name='expenseattachment',
            name='file',
            field=models.FileField(upload_to=expenses.models.expense_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='Dozvoljeni formati: PDF, JPG, PNG.'), expenses.validators.validate_invoice_file_size, expenses.validators.validate_invoice_file_content], verbose_name='Prilog računa'),
        ),
        migrations.AlterField(
            model_name='expensepayer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
