# Generated by Django 4.2.7 on 2026-08-23 17:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('expenses', '0014_expensecategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Redoslijed')),
                ('description', models.TextField(verbose_name='Opis stavke')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Osnovica')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Iznos PDV-a')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Iznos s PDV-om')),
                ('vehicle_line_kind', models.CharField(blank=True, choices=[('technical_inspection_service', 'Tehnički pregled'), ('registration_admin_service', 'Administracija registracije'), ('road_fee_annual', 'Godišnja naknada za ceste'), ('environmental_fee', 'Naknada za okoliš'), ('administrative_fee', 'Upravna pristojba'), ('motor_vehicle_tax', 'Porez na cestovna motorna vozila'), ('insurance_compulsory', 'Obvezno osiguranje'), ('unclassified', 'Neklasificirano')], help_text='Činjenica s isprave. NULL = nije provedeno ili nije primjenjivo; unclassified = pokušano, nije prepoznato.', max_length=64, null=True, verbose_name='Vrsta stavke vozila')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='expenses.expense', verbose_name='Trošak')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Stavka troška',
                'verbose_name_plural': 'Stavke troška',
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.UniqueConstraint(fields=('expense', 'position'), name='unique_expense_line_position_per_expense'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(check=models.Q(('vehicle_line_kind', ''), _negated=True), name='expense_line_kind_not_empty_string'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(check=models.Q(('description', ''), _negated=True), name='expense_line_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 1)), name='expense_line_position_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', 0), ('vat_amount__gte', 0), ('gross_amount__gte', 0)), name='expense_line_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='expenseline',
            constraint=models.CheckConstraint(check=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('net_amount'), '+', models.F('vat_amount')))), name='expense_line_gross_equals_net_plus_vat'),
        ),
    ]
