# Generated by Django 4.2.7 on 2026-08-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_vehicle'),
        ('expenses', '0015_expenseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Operativna pripadnost troška vozilu. Ne utječe na knjiženje.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='accounting.vehicle', verbose_name='Vozilo'),
        ),
    ]
