# Generated by Django 4.2.7 on 2026-09-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_expense_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Ručno'), ('super', 'SUPER'), ('f1_csv', 'F1 CSV'), ('ocr', 'OCR'), ('email', 'E-mail'), ('eracun', 'eRačun')], default='manual', max_length=20, verbose_name='Izvor'),
        ),
        migrations.AlterField(
            model_name='expenseimportmetadata',
            name='source',
            field=models.CharField(choices=[('manual', 'Ručno'), ('super', 'SUPER'), ('f1_csv', 'F1 CSV'), ('ocr', 'OCR'), ('email', 'E-mail'), ('eracun', 'eRačun')], max_length=20, verbose_name='Izvor'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='source',
            field=models.CharField(choices=[('manual', 'Ručno'), ('super', 'SUPER'), ('f1_csv', 'F1 CSV'), ('ocr', 'OCR'), ('email', 'E-mail'), ('eracun', 'eRačun')], max_length=20, verbose_name='Izvor'),
        ),
    ]
