# Generated by Django 4.2.7 on 2026-09-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounting_module_expansion'),
        ('expenses', '0018_expense_source_eracun'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseline',
            name='expense_account',
            field=models.ForeignKey(
                blank=True,
                help_text='Override debita za ovu stavku. NULL = header konto (postojeći tok).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='expense_line_account_overrides',
                to='accounting.chartofaccounts',
                verbose_name='Konto stavke',
            ),
        ),
    ]
