# Generated by Django 4.2.7 on 2026-09-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_accounting_module_expansion'),
        ('expenses', '0019_expenseline_expense_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenseline',
            old_name='expense_account',
            new_name='posting_account',
        ),
        migrations.AlterField(
            model_name='expenseline',
            name='posting_account',
            field=models.ForeignKey(
                blank=True,
                help_text='Konto knjiženja za ovu stavku. NULL = header konto (postojeći tok).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='expense_line_posting_accounts',
                to='accounting.chartofaccounts',
                verbose_name='Konto stavke',
            ),
        ),
    ]
