# Generated by Django 4.2.7 on 2025-09-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_number', models.CharField(max_length=50, verbose_name='Broj izvoda')),
                ('statement_date', models.DateField(verbose_name='Datum izvoda')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Početno stanje')),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Završno stanje')),
                ('status', models.CharField(choices=[('imported', 'Uvezen'), ('reconciled', 'Usklađen'), ('archived', 'Arhiviran')], default='imported', max_length=10, verbose_name='Status')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum uvoza')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Datum usklađivanja')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='payments.bankaccount', verbose_name='Bankovni račun')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uvezao')),
            ],
            options={
                'verbose_name': 'Bankovni izvod',
                'verbose_name_plural': 'Bankovni izvodi',
                'ordering': ['-statement_date', '-statement_number'],
                'unique_together': {('bank_account', 'statement_number')},
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankstatement')),
            ],
        ),
    ]
