# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(fields=('tenant', 'bank_account', 'statement_number'), name='unique_statement_per_tenant_account'),
        ),
    ]
