# Generated by Django 4.2.7 on 2026-07-02 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('payments', '0004_eur_default_currency'),
        ('banking', '0005_banktransaction_tenant_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bankovni API poziv',
                'verbose_name_plural': 'Bankovni API pozivi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Odspojeno'), ('active', 'Aktivno'), ('error', 'Greška')], default='disconnected', max_length=20)),
                ('external_account_id', models.CharField(blank=True, max_length=100)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bankovna veza',
                'verbose_name_plural': 'Bankovne veze',
            },
        ),
        migrations.CreateModel(
            name='BankConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(blank=True, max_length=100)),
                ('authorization_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Primljen'), ('rejected', 'Odbijen'), ('valid', 'Valjan'), ('authorized', 'Autoriziran'), ('revoked', 'Opozvan'), ('expired', 'Istekao')], default='received', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bankovni consent',
                'verbose_name_plural': 'Bankovni consenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankPaymentInitiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiation_id', models.CharField(blank=True, max_length=100)),
                ('authorization_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('received', 'Primljen'), ('pending', 'Na čekanju SCA'), ('accepted', 'Prihvaćen'), ('rejected', 'Odbijen'), ('cancelled', 'Otkazan')], default='received', max_length=20)),
                ('sca_redirect_url', models.URLField(blank=True)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bankovna inicijacija plaćanja',
                'verbose_name_plural': 'Bankovne inicijacije plaćanja',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Šifra')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Produkcija')], max_length=20)),
                ('iam_base', models.URLField(verbose_name='IAM baza')),
                ('api_base', models.URLField(verbose_name='API baza')),
                ('service_host', models.CharField(max_length=255, verbose_name='Servisni host')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bankovni provider',
                'verbose_name_plural': 'Bankovni provideri',
            },
        ),
        migrations.CreateModel(
            name='BankWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bankovni webhook',
                'verbose_name_plural': 'Bankovni webhookovi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['transaction_date', 'id'], 'verbose_name': 'Bankovna transakcija', 'verbose_name_plural': 'Bankovne transakcije'},
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vanjski ID'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('tenant', 'bank_statement', 'external_id'), name='unique_external_tx_per_statement'),
        ),
        migrations.AddField(
            model_name='bankwebhookevent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='banking.bankprovider'),
        ),
        migrations.AddField(
            model_name='bankwebhookevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='bankpaymentinitiation',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_initiations', to='banking.bankconnection'),
        ),
        migrations.AddField(
            model_name='bankpaymentinitiation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_initiations', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='bankpaymentinitiation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='bankconsent',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='banking.bankconnection'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to='payments.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='bank_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='banking.bankprovider'),
        ),
        migrations.AddField(
            model_name='bankconnection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='bankapicall',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_calls', to='banking.bankprovider'),
        ),
        migrations.AddField(
            model_name='bankapicall',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_api_calls', to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='bankconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'bank_provider', 'bank_account'), name='unique_bank_connection_per_tenant'),
        ),
    ]
