# Generated by Django 4.2.7 on 2026-07-04 09:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('payments', '0006_bankaccount_ledger_account'),
        ('banking', '0009_banktransaction_journal_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_product', models.CharField(choices=[('domestic-payment', 'Domaće plaćanje'), ('sepa-credit-transfers', 'SEPA credit transfer')], default='domestic-payment', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Nacrt'), ('submitted', 'Poslan'), ('sca_required', 'SCA potreban'), ('authorised', 'Autoriziran'), ('accepted', 'Prihvaćen'), ('executed', 'Izvršen'), ('rejected', 'Odbijen'), ('failed', 'Neuspješan')], default='draft', max_length=20)),
                ('otp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='OTP paymentId')),
                ('authorization_id', models.CharField(blank=True, max_length=100)),
                ('sca_redirect_url', models.URLField(blank=True)),
                ('debtor_iban', models.CharField(max_length=34)),
                ('creditor_iban', models.CharField(max_length=34)),
                ('creditor_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('reference', models.CharField(blank=True, max_length=140)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='banking.bankconnection')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_orders', to='payments.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'PIS nalog',
                'verbose_name_plural': 'PIS nalozi',
                'ordering': ['-created_at'],
            },
        ),
    ]
