# Generated by Django 4.2.7 on 2026-08-19 17:25

import banking.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0015_remove_bankpaymentinitiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='paymentexecutiontransition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='payment_product',
            field=models.CharField(choices=[('domestic-payment', 'Domaće plaćanje'), ('sepa-credit-transfers', 'SEPA credit transfer')], default='sepa-credit-transfers', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentordertransition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.CreateModel(
            name='BankImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('upload', 'Upload')], default='upload', max_length=20)),
                ('format', models.CharField(blank=True, max_length=20, verbose_name='Format')),
                ('original_filename', models.CharField(blank=True, max_length=200)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('payload', models.FileField(blank=True, upload_to=banking.models.bank_import_payload_upload_to, verbose_name='Datoteka')),
                ('status', models.CharField(choices=[('queued', 'U redu'), ('running', 'U tijeku'), ('succeeded', 'Uspješno'), ('failed', 'Neuspješno'), ('rejected', 'Odbijeno')], db_index=True, default='queued', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('statements_processed', models.PositiveIntegerField(default=0)),
                ('statements_created', models.PositiveIntegerField(default=0)),
                ('statements_updated', models.PositiveIntegerField(default=0)),
                ('transactions_processed', models.PositiveIntegerField(default=0)),
                ('transactions_created', models.PositiveIntegerField(default=0)),
                ('transactions_skipped', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_import_runs', to=settings.AUTH_USER_MODEL, verbose_name='Pokrenuo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Uvoz bankovnog izvoda',
                'verbose_name_plural': 'Uvozi bankovnih izvoda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'U redu'), ('running', 'U tijeku'), ('succeeded', 'Uspješno'), ('failed', 'Neuspješno')], db_index=True, default='queued', max_length=20)),
                ('transactions_created', models.PositiveIntegerField(default=0)),
                ('transactions_skipped', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('auto_create_payments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_sync_runs', to=settings.AUTH_USER_MODEL, verbose_name='Pokrenuo')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='banking.bankconnection', verbose_name='Veza')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Sinkronizacija banke',
                'verbose_name_plural': 'Sinkronizacije banke',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'connection', '-created_at'], name='banksyncrun_tenant_conn'), models.Index(fields=['status', '-created_at'], name='banksyncrun_status')],
            },
        ),
        migrations.AddConstraint(
            model_name='banksyncrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running'])), fields=('connection',), name='unique_active_bank_sync_per_connection'),
        ),
        migrations.AddIndex(
            model_name='bankimportrun',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='bankimportrun_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='bankimportrun',
            index=models.Index(fields=['tenant', 'content_sha256'], name='bankimportrun_tenant_sha'),
        ),
        migrations.AddConstraint(
            model_name='bankimportrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'actor', 'idempotency_key'), name='unique_bank_import_idempotency_per_actor'),
        ),
    ]
