# Generated by Django 4.2.7 on 2026-08-20 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_create_finestar_tenant'),
        ('banking', '0017_bank_match_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconcileIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('subledger_item_id', models.PositiveIntegerField()),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconcile_idempotency_keys', to='banking.banktransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Idempotency usklađivanja',
                'verbose_name_plural': 'Idempotency usklađivanja',
            },
        ),
        migrations.AddConstraint(
            model_name='bankreconcileidempotency',
            constraint=models.UniqueConstraint(fields=('tenant', 'bank_transaction', 'idempotency_key'), name='unique_bank_reconcile_idempotency'),
        ),
    ]
