# Generated by Django 4.2.7 on 2025-09-07 10:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100, verbose_name='Naziv računa')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Naziv banke')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Broj računa')),
                ('iban', models.CharField(max_length=34, unique=True, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=11, verbose_name='SWIFT kod')),
                ('currency', models.CharField(default='HRK', max_length=3, verbose_name='Valuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
            ],
            options={
                'verbose_name': 'Bankovni račun',
                'verbose_name_plural': 'Bankovni računi',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Broj uplate/isplate')),
                ('payment_type', models.CharField(choices=[('incoming', 'Uplata'), ('outgoing', 'Isplata')], max_length=10, verbose_name='Tip plaćanja')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bankovni transfer'), ('cash', 'Gotovina'), ('card', 'Kartica'), ('check', 'Ček'), ('other', 'Ostalo')], max_length=15, verbose_name='Način plaćanja')),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('completed', 'Završeno'), ('failed', 'Neuspješno'), ('cancelled', 'Otkazano')], default='pending', max_length=10, verbose_name='Status')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Iznos')),
                ('currency', models.CharField(default='HRK', max_length=3, verbose_name='Valuta')),
                ('payment_date', models.DateField(verbose_name='Datum plaćanja')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Datum valute')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('reference_number', models.CharField(blank=True, max_length=50, verbose_name='Poziv na broj')),
                ('counterparty_name', models.CharField(blank=True, max_length=200, verbose_name='Naziv druge strane')),
                ('counterparty_account', models.CharField(blank=True, max_length=50, verbose_name='Račun druge strane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum ažuriranja')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.bankaccount', verbose_name='Bankovni račun')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kreirao')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.invoice', verbose_name='Povezani račun')),
            ],
            options={
                'verbose_name': 'Plaćanje',
                'verbose_name_plural': 'Plaćanja',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
