# Generated by Django 4.2.7 on 2025-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.TextField()),
                ('company_phone', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_website', models.URLField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('timezone', models.CharField(default='Europe/Zagreb', max_length=50)),
                ('date_format', models.CharField(default='d.m.Y', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
            ],
        ),
    ]
