# Generated by Django 4.2.7 on 2025-09-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Postavke tvrtke', 'verbose_name_plural': 'Postavke tvrtke'},
        ),
        migrations.AlterModelOptions(
            name='systemparameter',
            options={'verbose_name': 'Sistemski parametar', 'verbose_name_plural': 'Sistemski parametri'},
        ),
    ]
