# Generated by Django 4.2.7 on 2025-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_companysettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_address',
            field=models.TextField(verbose_name='Adresa tvrtke'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_email',
            field=models.EmailField(max_length=254, verbose_name='Email tvrtke'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo tvrtke'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='Naziv tvrtke'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_phone',
            field=models.CharField(max_length=50, verbose_name='Telefon tvrtke'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='Web stranica'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Kreirano'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='date_format',
            field=models.CharField(default='d.m.Y', max_length=20, verbose_name='Format datuma'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Zadana valuta'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=5, verbose_name='Zadana stopa PDV-a (%)'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='timezone',
            field=models.CharField(default='Europe/Zagreb', max_length=50, verbose_name='Vremenska zona'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ažurirano'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='data_type',
            field=models.CharField(choices=[('string', 'Tekst'), ('integer', 'Broj'), ('float', 'Decimalni broj'), ('boolean', 'Da/Ne'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tip podatka'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ključ'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='value',
            field=models.TextField(verbose_name='Vrijednost'),
        ),
    ]
