# Generated by Django 4.2.7 on 2025-09-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_companysettings_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stopa (%)')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('is_default', models.BooleanField(default=False, verbose_name='Zadana stopa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
            ],
            options={
                'verbose_name': 'Porezna stopa',
                'verbose_name_plural': 'Porezne stope',
                'ordering': ['rate'],
            },
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.taxrate', verbose_name='Zadana porezna stopa'),
        ),
    ]
