# Generated by Django 4.2.7 on 2025-09-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_taxrate_alter_companysettings_default_tax_rate'),
    ]

    operations = [
    ]
