# Generated by Django 4.2.7 on 2025-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20250907_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Matični broj'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='tax_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Porezni broj'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='OIB/VAT broj'),
        ),
    ]
