# Generated by Django 4.2.7 on 2025-09-07 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_companysettings_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('director', 'Direktor'), ('ceo', 'Glavni izvršni direktor (CEO)'), ('cfo', 'Financijski direktor (CFO)'), ('coo', 'Operativni direktor (COO)'), ('deputy_director', 'Zamjenik direktora'), ('prokurist', 'Prokurist'), ('manager', 'Manager'), ('department_head', 'Voditelj odjela'), ('accountant', 'Računovođa'), ('secretary', 'Tajnik'), ('legal_representative', 'Zakonski zastupnik'), ('authorized_person', 'Ovlaštena osoba'), ('other', 'Ostalo')], max_length=50, verbose_name='Titula/Funkcija')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=100, verbose_name='Prezime')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Glavna kontakt osoba')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivna')),
                ('notes', models.TextField(blank=True, verbose_name='Napomene')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažurirano')),
                ('company_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_persons', to='settings.companysettings', verbose_name='Postavke tvrtke')),
            ],
            options={
                'verbose_name': 'Odgovorna osoba',
                'verbose_name_plural': 'Odgovorne osobe',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['company_settings', 'is_active'], name='settings_re_company_68eb7b_idx'), models.Index(fields=['is_primary'], name='settings_re_is_prim_64e6ed_idx')],
            },
        ),
    ]
