# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('settings', '0007_responsibleperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Ključ'),
        ),
        migrations.AddConstraint(
            model_name='systemparameter',
            constraint=models.UniqueConstraint(fields=('tenant', 'key'), name='unique_system_param_per_tenant'),
        ),
    ]
