"""Sinkronizacija Traefik dynamic routera za custom domene."""

from __future__ import annotations

from pathlib import Path

from django.conf import settings

from tenants.models import Tenant
from tenants.resolution import invalidate_custom_domain_cache, normalize_host


def get_traefik_dynamic_path() -> Path:
    return Path(getattr(
        settings,
        'TENANT_TRAEFIK_DYNAMIC_PATH',
        '/opt/stacks/traefik/dynamic/racunai-erp-custom.yml',
    ))


def build_traefik_yaml(tenants=None) -> str:
    if tenants is None:
        tenants = Tenant.objects.filter(is_active=True).exclude(custom_domain__isnull=True).exclude(custom_domain='')

    cert_resolver = getattr(settings, 'TENANT_CUSTOM_DOMAIN_CERT_RESOLVER', 'cloudflare')
    lines = [
        '# Auto-generated by racunai ERP — sync_custom_domain_routers',
        '# Do not edit manually; changes are overwritten on Tenant save.',
    ]

    active = []
    for tenant in tenants:
        host = normalize_host(tenant.custom_domain)
        if host:
            active.append((tenant.slug, host))

    if not active:
        lines.append('# No custom domains configured.')
        return '\n'.join(lines) + '\n'

    lines.extend(['http:', '  routers:'])
    for slug, host in active:
        router_name = f'racunai-erp-custom-{slug}'
        lines.extend([
            f'    {router_name}:',
            f'      rule: Host(`{host}`)',
            '      entryPoints:',
            '        - websecure',
            '      service: racunai-erp@docker',
            '      priority: 90',
            '      tls:',
            f'        certResolver: {cert_resolver}',
        ])

    return '\n'.join(lines) + '\n'


def sync_traefik_custom_domains(tenants=None) -> Path:
    content = build_traefik_yaml(tenants)
    path = get_traefik_dynamic_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    invalidate_custom_domain_cache()
    return path
