# Generated by Django 4.2.7 on 2026-06-08 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Naziv')),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Prilagođena domena')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenanti',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Vlasnik'), ('accountant', 'Računovođa'), ('viewer', 'Pregled')], max_length=20, verbose_name='Uloga')),
                ('is_default', models.BooleanField(default=False, verbose_name='Zadani tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Članstvo u tenantu',
                'verbose_name_plural': 'Članstva u tenantima',
                'ordering': ['tenant__name', 'user__username'],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
