# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_seed_finestar_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(unique=True, validators=[tenants.models.validate_tenant_slug], verbose_name='Slug'),
        ),
    ]
