# Generated by Django 4.2.7 on 2026-06-08 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0004_backfill_finestar_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('role', models.CharField(choices=[('owner', 'Vlasnik'), ('accountant', 'Računovođa'), ('viewer', 'Pregled')], max_length=20, verbose_name='Uloga')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('accepted', 'Prihvaćeno'), ('revoked', 'Opozvano'), ('expired', 'Isteklo')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kreirano')),
                ('expires_at', models.DateTimeField(verbose_name='Istječe')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Prihvaćeno')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Pozvao')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Pozivnica',
                'verbose_name_plural': 'Pozivnice',
                'ordering': ['-created_at'],
            },
        ),
    ]
