# Generated by Django 4.2.7 on 2025-09-07 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpimetric',
            options={'ordering': ['-date'], 'verbose_name': 'KPI metrika', 'verbose_name_plural': 'KPI metrike'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Obavijest', 'verbose_name_plural': 'Obavijesti'},
        ),
    ]
