# Generated by Django 4.2.7 on 2026-06-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_add_tenant_fields'),
        ('dashboard', '0002_alter_kpimetric_options_alter_notification_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kpimetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kpimetric',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddConstraint(
            model_name='kpimetric',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'date'), name='unique_kpi_per_tenant_date'),
        ),
    ]
